#
# Autogenerated by Thrift Compiler (0.11.0)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING


module PAR2

using Compat
using Thrift
import Thrift.process, Thrift.meta, Thrift.distribute




export meta
export _Type # enum
export ConvertedType # enum
export FieldRepetitionType # enum
export Encoding # enum
export CompressionCodec # enum
export PageType # enum
export Statistics # struct
export SchemaElement # struct
export DataPageHeader # struct
export IndexPageHeader # struct
export DictionaryPageHeader # struct
export DataPageHeaderV2 # struct
export PageHeader # struct
export KeyValue # struct
export SortingColumn # struct
export PageEncodingStats # struct
export ColumnMetaData # struct
export ColumnChunk # struct
export RowGroup # struct
export FileMetaData # struct

include("PAR2_constants.jl")
include("PAR2_types.jl")
include("PAR2_impl.jl")  # server methods to be hand coded


end # module PAR2
